export const API = {
  forecast: 'https://api.open-meteo.com/v1/forecast',
  geocoding: 'https://geocoding-api.open-meteo.com/v1/search',
  airQuality: 'https://air-quality-api.open-meteo.com/v1/air-quality',
  archive: 'https://archive-api.open-meteo.com/v1/archive',
  marine: 'https://marine-api.open-meteo.com/v1/marine',
};

export const STORAGE_KEYS = {
  unitSystem: 'weather_unit_sys',
  theme: 'weather_theme',
  lastLocation: 'weather_last_location',
  recent: 'weather_recent',
  favorites: 'weather_favorites',
  home: 'weather_home',
  snapshotHistory: 'weather_snapshot_history',
  locationPresets: 'weather_location_presets',
  sectionVisibility: 'weather_section_visibility_v1',
  compareLocations: 'weather_compare_locations_v1',
  mapView: 'weather_map_view_v1',
  mapWeatherPrefix: 'map_weather_cache_v1',
  radarFrames: 'weather_radar_frames_v1',
  appMode: 'weather_app_mode_v1',
  tourismPrefix: 'tourism_cache_v14',
  preferredCurrency: 'weather_preferred_currency_v1',
  livingCostApiKey: 'weather_livingcost_api_key_v1',
  currenciesCache: 'weather_currencies_cache_v2',
  fxPrefix: 'fx_v2',
  locationContextPrefix: 'location_context_v5',
  worldBankSafetyPrefix: 'worldbank_safety_v1',
  travelAdvisoryPrefix: 'travel_advisory_v2',
  wikivoyageSafetyPrefix: 'wikivoyage_safety_v1',
  runtimeLogs: 'weather_runtime_logs_v1',
};

export const CACHE = {
  schemaVersion: 3,
  prefix: 'weather_cache_v3',
  ttlMs: 10 * 60 * 1000,
  staleTtlMs: 24 * 60 * 60 * 1000,
  mapTtlMs: 20 * 60 * 1000,
  radarTtlMs: 6 * 60 * 1000,
};

export const TILE_PROVIDER = {
  name: 'OpenFreeMap Vector',
  template: 'https://tiles.openfreemap.org/styles/{style}',
  subdomains: [],
  minZoom: 1,
  maxZoom: 15.5,
  attribution: 'OpenFreeMap / OpenStreetMap | Dane: Open-Meteo',
};

export const SECTION_IDS = {
  alerts: 'alertsSection',
  comfort: 'comfortSection',
  clothing: 'clothingSection',
  nextHours: 'nextHoursSection',
  map: 'mapSection',
  aqi: 'aqiCard',
  history: 'historyCard',
  sport: 'sportSection',
  astronomy: 'astroSection',
  marine: 'marineSection',
  chart: 'chartSection',
  recommendations: 'insightsSection',
};

export const DEFAULT_SECTION_VISIBILITY = {
  alerts: true,
  comfort: true,
  clothing: true,
  nextHours: true,
  map: true,
  aqi: true,
  history: true,
  sport: true,
  astronomy: true,
  marine: true,
  chart: true,
  recommendations: true,
};

export const WMO_ICONS = {
  0: { icon: '☀️', label: 'Bezchmurnie' },
  1: { icon: '🌤️', label: 'Przeważnie słonecznie' },
  2: { icon: '⛅', label: 'Częściowe zachmurzenie' },
  3: { icon: '☁️', label: 'Zachmurzenie całkowite' },
  45: { icon: '🌫️', label: 'Mgła' },
  48: { icon: '🌫️', label: 'Szron mgielny' },
  51: { icon: '🌦️', label: 'Lekka mżawka' },
  53: { icon: '🌦️', label: 'Umiarkowana mżawka' },
  55: { icon: '🌧️', label: 'Silna mżawka' },
  61: { icon: '🌧️', label: 'Słaby deszcz' },
  63: { icon: '🌧️', label: 'Umiarkowany deszcz' },
  65: { icon: '🌧️', label: 'Silny deszcz' },
  71: { icon: '🌨️', label: 'Słaby śnieg' },
  73: { icon: '🌨️', label: 'Umiarkowany śnieg' },
  75: { icon: '❄️', label: 'Silny śnieg' },
  77: { icon: '🌨️', label: 'Ziarna śniegu' },
  80: { icon: '🌦️', label: 'Słabe przelotne opady' },
  81: { icon: '🌧️', label: 'Przelotne opady' },
  82: { icon: '⛈️', label: 'Silne przelotne opady' },
  85: { icon: '🌨️', label: 'Przelotny śnieg' },
  86: { icon: '❄️', label: 'Silny przelotny śnieg' },
  95: { icon: '⛈️', label: 'Burza' },
  96: { icon: '⛈️', label: 'Burza z gradem' },
  99: { icon: '⛈️', label: 'Burza z silnym gradem' },
};

export const MAP_CITIES_BY_ZOOM = {
  1: [
    { name: 'Warszawa', lat: 52.23, lon: 21.01 },
    { name: 'Berlin', lat: 52.52, lon: 13.4 },
    { name: 'Paryż', lat: 48.86, lon: 2.35 },
    { name: 'Londyn', lat: 51.51, lon: -0.13 },
    { name: 'Madryt', lat: 40.42, lon: -3.7 },
    { name: 'Rzym', lat: 41.9, lon: 12.5 },
    { name: 'Moskwa', lat: 55.75, lon: 37.62 },
    { name: 'Kijów', lat: 50.45, lon: 30.52 },
    { name: 'Sztokholm', lat: 59.33, lon: 18.07 },
    { name: 'Oslo', lat: 59.91, lon: 10.75 },
    { name: 'Ateny', lat: 37.98, lon: 23.73 },
    { name: 'Lizbona', lat: 38.72, lon: -9.14 },
    { name: 'Amsterdam', lat: 52.37, lon: 4.9 },
    { name: 'Wiedeń', lat: 48.21, lon: 16.37 },
    { name: 'Budapeszt', lat: 47.5, lon: 19.04 },
    { name: 'Bukareszt', lat: 44.43, lon: 26.1 },
    { name: 'Kopenhaga', lat: 55.68, lon: 12.57 },
    { name: 'Helsinki', lat: 60.17, lon: 24.94 },
  ],
  3: [
    { name: 'Kraków', lat: 50.06, lon: 19.94 },
    { name: 'Gdańsk', lat: 54.37, lon: 18.61 },
    { name: 'Wrocław', lat: 51.11, lon: 17.04 },
    { name: 'Poznań', lat: 52.41, lon: 16.93 },
    { name: 'Łódź', lat: 51.77, lon: 19.46 },
    { name: 'Szczecin', lat: 53.43, lon: 14.55 },
    { name: 'Praga', lat: 50.08, lon: 14.44 },
    { name: 'Bratysława', lat: 48.15, lon: 17.11 },
    { name: 'Zagrzeb', lat: 45.81, lon: 15.98 },
    { name: 'Belgrad', lat: 44.8, lon: 20.46 },
    { name: 'Sofia', lat: 42.7, lon: 23.32 },
    { name: 'Wilno', lat: 54.69, lon: 25.28 },
    { name: 'Ryga', lat: 56.95, lon: 24.11 },
    { name: 'Tallinn', lat: 59.44, lon: 24.75 },
    { name: 'Mińsk', lat: 53.9, lon: 27.57 },
    { name: 'Barcelona', lat: 41.39, lon: 2.17 },
    { name: 'Marsylia', lat: 43.3, lon: 5.37 },
    { name: 'Lyon', lat: 45.75, lon: 4.85 },
    { name: 'Hamburg', lat: 53.55, lon: 10 },
    { name: 'Monachium', lat: 48.14, lon: 11.58 },
    { name: 'Frankfurt', lat: 50.11, lon: 8.68 },
    { name: 'Kolonia', lat: 50.94, lon: 6.96 },
    { name: 'Mediolan', lat: 45.46, lon: 9.19 },
    { name: 'Neapol', lat: 40.85, lon: 14.27 },
  ],
  5: [
    { name: 'Bydgoszcz', lat: 53.12, lon: 18 },
    { name: 'Lublin', lat: 51.25, lon: 22.57 },
    { name: 'Białystok', lat: 53.13, lon: 23.16 },
    { name: 'Katowice', lat: 50.26, lon: 19.02 },
    { name: 'Rzeszów', lat: 50.04, lon: 22 },
    { name: 'Olsztyn', lat: 53.78, lon: 20.49 },
    { name: 'Kielce', lat: 50.87, lon: 20.63 },
    { name: 'Toruń', lat: 53.01, lon: 18.61 },
    { name: 'Gorzów', lat: 52.73, lon: 15.23 },
    { name: 'Opole', lat: 50.67, lon: 17.92 },
    { name: 'Drezno', lat: 51.05, lon: 13.74 },
    { name: 'Lipsk', lat: 51.34, lon: 12.37 },
    { name: 'Stuttgart', lat: 48.78, lon: 9.18 },
    { name: 'Düsseldorf', lat: 51.22, lon: 6.78 },
    { name: 'Bruksela', lat: 50.85, lon: 4.35 },
    { name: 'Luksemburg', lat: 49.61, lon: 6.13 },
    { name: 'Zurych', lat: 47.38, lon: 8.54 },
    { name: 'Genewa', lat: 46.2, lon: 6.15 },
    { name: 'Tuluza', lat: 43.6, lon: 1.44 },
    { name: 'Bordeaux', lat: 44.84, lon: -0.58 },
    { name: 'Sewilla', lat: 37.39, lon: -5.99 },
    { name: 'Walencja', lat: 39.47, lon: -0.38 },
    { name: 'Porto', lat: 41.16, lon: -8.62 },
    { name: 'Brno', lat: 49.19, lon: 16.61 },
    { name: 'Ostrawa', lat: 49.83, lon: 18.29 },
    { name: 'Gdynia', lat: 54.52, lon: 18.53 },
    { name: 'Sosnowiec', lat: 50.29, lon: 19.1 },
    { name: 'Radom', lat: 51.4, lon: 21.15 },
  ],
};
